global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'node-api'
    static_configs:
      - targets: ["node-api-app:8001"]

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          instance: 'postgresql'
